Feature/main/246 scrape pillowfort
philomena-dev/philomena pull request #139
Opened 2021-09-26 19:17 UTC by Erhannis

### Before you begin

* I understand my contributions may be rejected for any reason
* I understand my contributions are for the benefit of Derpibooru and/or the Philomena software
* I understand my contributions are licensed under the GNU AGPLv3

- [X] I understand all of the above

---

Added support for scraping Pillowfort urls.  I wasn't super sure about how robust we wanted to be to changes to Pillowfort's url, but it seems to work for now, anyway.

2021-09-26 19:28 UTC, Erhannis commented
Oh, I should comment explicitly that this is to resolve https://github.com/derpibooru/philomena/issues/246

2021-09-27 02:01 UTC, liamwhite requested changes

2021-09-27 02:01 UTC, liamwhite commented on lib/philomena/scrapers/pillowfort.ex
> +          camo_url: Camo.Image.image_url(&1["url"])
Does the API response have any preview-sized images or do you only ever get the full image?

2021-09-27 02:01 UTC, liamwhite commented on lib/philomena/scrapers/pillowfort.ex
> +      description: postJson["title"] <> "\n----\n" <> postJson["content"],
Would suggest using a [thematic break](https://github.com/chrisalley/markdown-garden/blob/master/source/guides/thematic-breaks.md) here

2021-12-20 03:39 UTC, liamwhite commented
This had no response for several months and it was basically done, so I just went ahead and finished it.

2021-12-20 03:39 UTC, merged