Update comrak to 0.18.0 (philomena fork)
philomena-dev/philomena pull request #179
Opened 2023-04-21 02:47 UTC by liamwhite

This updates comrak to 0.18.0 with philomena changes ported forward.

Note: we might also want to merge the changes from [here](https://github.com/philomena-dev/comrak/tree/no-empty-inlines-in-links) to help resolve some issues with hidden links?

2023-04-21 07:34 UTC, Meow commented
I would wait until we can test it out locally, ensure everything works, and then just keep main philomena on the main branch rather than switching branch via this PR.

I am on board with not parsing empty-text links.

2023-04-21 07:34 UTC, Meow requested changes
(see previous comment)

2023-04-22 14:59 UTC, liamwhite commented
Commits applied to main branch now

2023-04-22 18:01 UTC, Meow approved these changes
lgtm

2023-04-22 18:01 UTC, merged