Public filter search
philomena-dev/philomena pull request #88
Opened 2021-01-09 15:49 UTC by VcSaJen

### Before you begin

* I understand my contributions may be rejected for any reason
* I understand my contributions are for the benefit of Derpibooru and/or the Philomena software
* I understand my contributions are licensed under the GNU AGPLv3

- [x] I understand all of the above

---

Restores public filter search functionality from booru-on-rails.
1. I'm not sure on how ElasticSearch migrations are done. Is reindex triggered manually? Should I add "Reindex All Filters" button?
2. Some filter fields are not visible to the user, so I'm not sure if it should be included in search. `created_at` field is not visible to both UI and API (I included it for now). `user_count` is not visible to UI, but visible on API (I did not include it yet). If `user_count` is safe to include, then it would be nice to sort by this field so that popular filters are on the top.
3. I also wanted to add search by hidden/spoilered tags, but looks like there's no way to preload hidden/spoilered tags on Filter query. I can do DB query on `as_json()`, but I assume it shouldn't be done that way?

2021-01-11 18:09 UTC, liamwhite commented
Sorry I have not responded to this promptly as my old computer died and I am waiting for my new computer to arrive.

1. At this time they're triggered manually on deployment because Elasticsearch provides absolutely no help for schema management.
2. `created_at`, `updated_at` etc is fine to include. In fact it's fine to index everything inside the filter. The reason `user_count` is not visible/present is because it's no longer updated (this is due to normalization errors, it could be restored later once `users.current_filter` is normalized). Which brings me to...
3. This is another normalization error. I would say just add the fields to the index for now and let them remain unused until that occurs.

2021-01-11 18:16 UTC, liamwhite commented
Also, it doesn't seem like you should need the query-time transforms in the parser definition. Adding this filter in the controller for non-staff users should be sufficient. (Make sure to check that the `current_user` is not `nil` first.)

```elixir
%{
  "bool":
    %{
      "should": [
        %{"term": %{"user_id": current_user.id}},
        %{"term": %{"public": true}
      ]
    }
}
```

2021-01-12 00:46 UTC, VcSaJen commented
@liamwhite thanks, I'll add them.
@liamwhite I'm already using `should`.

2021-01-14 15:43 UTC, VcSaJen commented
Made changes according to comment.

2021-01-14 22:24 UTC, liamwhite requested changes
Just a few things.

2021-01-14 22:24 UTC, liamwhite commented on lib/mix/tasks/reindex_all.ex
> -    Tags.Tag
You should also add an indexing script for filters in `index/`

2021-01-14 22:24 UTC, liamwhite commented on lib/philomena/filters/elasticsearch_index.ex
> +          name: %{
In my opinion, name should be indexed as literal (keyword)

2021-01-14 22:24 UTC, liamwhite commented on lib/philomena/filters/elasticsearch_index.ex
> +          spoilers_namespaced_tags: %{
use `spoilered_tags` and `hidden_tags` for these field names and just make them arrays directly on the root document:
```elixir
  spoilered_tags: %{type: "keyword"},
  hidden_tags: %{type: "keyword"},
```

2021-01-14 22:24 UTC, liamwhite commented on lib/philomena/filters/elasticsearch_index.ex
> +          hidden_complex_str: %{type: "wildcard"},
The `wildcard` field type belongs to X-Pack. X-Pack is available for free but does not contain a compatible license with the project. This should use `keyword` instead.

2021-01-14 22:24 UTC, liamwhite commented on lib/philomena/filters/query.ex
> +  defp user_id_transform(_ctx, data) do
Neither `user_id_transform` nor `creator_transform` here should be necessary due to the controller level filtering. The filter applied at the controller level ensures that either the returned filter is public or that it belongs to the user.

2021-01-14 22:24 UTC, liamwhite commented on lib/philomena/filters/query.ex
> +      aliases: %{"title" => "name", "maintainer" => "creator"}
Purpose of these aliases?

2021-01-17 07:38 UTC, VcSaJen commented
Made changes according to requested changes.
I added `; doc._id = doc.id` to transform parameter of elasticdump command in filters.mk, because I couldn't get it to generate correct indexes without it.

2021-01-17 23:15 UTC, liamwhite requested changes
Other than this, looks fine to me, I'll test and hopefully merge tomorrow

2021-01-17 23:15 UTC, liamwhite commented on lib/philomena/filters/query.ex
> +      ngram_fields: ~W(name description creator user_id),
`name`, `creator`, and `user_id` are `literal_fields`, not `ngram_fields`

2021-01-17 23:32 UTC, VcSaJen commented
I'll fix that. Should I squash and rebase?

2021-01-18 00:13 UTC, liamwhite commented
Just push a correction, no need to rebase

2021-01-18 18:00 UTC, liamwhite approved these changes

2021-01-18 18:00 UTC, merged